---
title: "12-03-19"
author: "Szumin Yu"
date: "12/4/2019"
output: html_document
---

Change settings & Load packages

```{r message=F, eval=F}

options(stringsAsFactors = F)
options(scipen = 999)

library(tidyverse)
library(ggplot2)
library(tidytuesdayR)
library(choroplethrZip)
library(ggalt)

```

Get data

```{r}
data = tidytuesdayR::tt_load('2019-12-03')
tkt = data$tickets
```

Inspect data
```{r}

#what violation happens most?
top_vio = tkt %>%
  count(violation_desc) %>%
  arrange(desc(n)) %>%
  slice(1:6)


#when does violation happen?
vio_hour = tkt %>%
  separate(issue_datetime, sep = ' ', into = c('date', 'time')) %>%
  mutate(time = lubridate::hms(time), hour = lubridate::hour(time)) 
##insepect - after maybe 11 or 12. so the afternoon
vio_hour %>% 
  count(hour) %>%
  arrange(desc(n)) %>%
  mutate(hour = fct_reorder(factor(hour), n)) %>%
  ggplot() +
  geom_bar(mapping = aes(x = hour, y = n), stat = 'identity')+
  coord_flip()

##filter top 5 violations

vio_hour %>%
  filter(violation_desc == top_vio$violation_desc) %>%
  ggplot()+
  geom_bar(mapping = aes(x = hour, fill = violation_desc), stat = 'count', width = 0.5) +
  scale_fill_brewer(name = 'Top 6 violations', palette = 'RdYlBu') + 
  scale_x_continuous(labels = c(0:23), breaks = c(0:23), limits = c(0,23)) +
  scale_y_continuous(label = scales::comma)+
  labs(title = 'Which time of the day did violations happen in Philly?',x = NULL, y = NULL) +
  guides(fill = guide_legend(nrow =2))+
  theme(text = element_text(family = 'Calibri'),
        plot.title = element_text(hjust = 0.5, size = 14, colour = '#ffffff'),
        plot.subtitle = element_text(hjust = 0.5, size = 13),
        plot.background = element_rect(fill = "#000000", color = "#000000"),
        axis.text = element_text(colour = '#ffffff'),
        legend.position = 'bottom',
        legend.title = element_text(family = 'Calibri',size = 10, colour = '#ffffff'),
        legend.text = element_text(family = 'Calibri',size = 9, colour = '#ffffff'),
        legend.background = element_rect(fill = "#000000", colour = '#000000'),
        legend.key = element_rect(colour = '#000000', size = 1),
        panel.background = element_rect(fill = "#000000"),
        panel.grid = element_blank())

ggsave('vio_philly.png', width=25, height = 15, units = 'cm')
```
